// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package listas

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/vinifrancosilva/lista_v2/internal/models"

func CriarLista(usuarios []models.Usuario) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section id=\"form_cria_lista\" class=\"w-full max-w-lg mx-auto px-4\" data-signals=\"{criarLista: ''}\"><div class=\"flex w-full flex-col gap-4\"><fieldset class=\"fieldset\"><legend class=\"fieldset-legend\">Criar nova lista</legend><div class=\"join\"><input data-bind:criarLista type=\"text\" class=\"input input-bordered w-full\" placeholder=\"Nome da nova lista...\" required data-on:keydown=\"evt.code == 'Enter' && @post('/api/lista/create')\"> <button class=\"btn btn-primary\" data-on:click=\"@post('/api/lista/create')\">Criar</button></div></fieldset></div><div data-show=\"$input_lista_erro !== ''\" role=\"alert\" class=\"alert alert-error alert-soft mt-2 hidden\" data-class=\"{hidden: $input_lista_erro === ''}\"><svg xmlns=\"http://www.w3.org/2000/svg\" class=\"h-6 w-6 shrink-0 stroke-current\" fill=\"none\" viewBox=\"0 0 24 24\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z\"></path></svg> <span data-text=\"$input_lista_erro\"></span></div><div data-show=\"$input_lista_sucesso !== ''\" role=\"alert\" class=\"alert alert-success alert-soft mt-2 hidden\" data-class=\"{hidden: $input_lista_sucesso === ''}\"><svg xmlns=\"http://www.w3.org/2000/svg\" class=\"h-6 w-6 shrink-0 stroke-current\" fill=\"none\" viewBox=\"0 0 24 24\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z\"></path></svg> <span data-text=\"$input_lista_sucesso\"></span></div></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
