services:
  postgres:
    user: "${DOCKER_UID}"
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: listas
      TZ: America/Sao_Paulo
      PGTZ: America/Sao_Paulo
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    restart: always
    networks:
      - postgres-network

  pgadmin:
    user: "${DOCKER_UID}"
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - ./postgres/pgadmin:/var/lib/pgadmin
    restart: always
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge
