version: "3"

dotenv: ['.env']
env:
  STATIC_DIR: "static"
  PATH: "{{.HOME}}/go/bin:{{.PATH}}"
  # POSTGRES_URL: "postgres://{{.ENV.DB_USER}}:{{.ENV.DB_PASSWORD}}@{{.ENV.DB_HOST}}:{{.ENV.DB_PORT}}/{{.ENV.DB_NAME}}?sslmode={{.ENV.DB_SSLMODE}}&search_path={{.ENV.DB_SEARCH_PATH}}"
  POSTGRES_URL: "postgres://postgres:postgres@localhost:5432/vinifranco?sslmode=disable&search_path=listas"

tasks:
  tools:
    cmds:
      - go install github.com/a-h/templ/cmd/templ@latest
      - go install github.com/air-verse/air@latest
      - go install github.com/go-delve/delve/cmd/dlv@latest
      - go install github.com/go-task/task/v3/cmd/task@latest

  # The `build:` tasks below are used together for "production" builds of your project
  build:templ:
    cmds:
      - templ generate
    sources:
      - "./views/**/*.templ"
    generates:
      - "./views/**/*_templ.go"

  build:styles:
    cmds:
      - pnpm exec tailwindcss -i views/styles/styles.css -o $STATIC_DIR/css/index.css
    sources:
      - "./views/**/*.html"
      - "./views/**/*.ts"
      - "./views/**/*.templ"
      - "./views/**/*.go"
    generates:
      - "{{.STATIC_DIR}}/css/index.css"

  build:
    cmds:
      - go build -ldflags "-s -w" -o listas .
    deps:
      - build:templ
      # - build:esbuild
      - build:styles
      # - build:sqlc

  # Use this task to debug your project with the delve debugger
  debug:
    cmds:
      - dlv exec listas
    deps:
      - build

  # The `live:` tasks below are used together for "dev" builds and will live-reload your entire project
  live:templ:
    cmds:
      - templ generate --watch --open-browser=false

  live:styles:
    cmds:
      - pnpm exec tailwindcss -i views/styles/styles.css -o $STATIC_DIR/css/index.css --watch

  # live:esbuild:
  #   cmds:
  #     - pnpm exec esbuild web/libs/datastar/index.ts --sourcemap --bundle --outdir=$STATIC_DIR --watch

  live:server:
    env:
      dotenv: [".env"]
    cmds:
      - air

  live:
    parallel: true
    deps:
      - live:server
      - live:styles
      - live:templ

  run:
    cmds:
      - ./listas
    deps:
      - build

  cria_migration:
    cmds:
      - migrate create -ext sql -dir db/migrations -seq {{.CLI_ARGS}}

  migration_up:
    cmds:
      # - migrate -path db/migrations -database "{{.POSTGRES_URL}}" up
      - migrate -path db/migrations -database "{{.POSTGRES_URL}}" up

  migration_down:
    cmds:
      # - migrate -path db/migrations -database "{{.POSTGRES_URL}}" up
      - migrate -path db/migrations -database "{{.POSTGRES_URL}}" down