// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package models

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Categoria struct {
	ID           int32              `json:"id"`
	UsuarioID    int32              `json:"usuario_id"`
	Categoria    string             `json:"categoria"`
	CriadoEm     pgtype.Timestamptz `json:"criado_em"`
	AtualizadoEm pgtype.Timestamptz `json:"atualizado_em"`
}

type Compartilhamento struct {
	ID        int32              `json:"id"`
	ListaID   int32              `json:"lista_id"`
	UsuarioID int32              `json:"usuario_id"`
	CriadoEm  pgtype.Timestamptz `json:"criado_em"`
}

type Item struct {
	ID           int32              `json:"id"`
	ListaID      int32              `json:"lista_id"`
	CategoriaID  pgtype.Int4        `json:"categoria_id"`
	Item         string             `json:"item"`
	Feito        bool               `json:"feito"`
	CriadoEm     pgtype.Timestamptz `json:"criado_em"`
	AtualizadoEm pgtype.Timestamptz `json:"atualizado_em"`
}

type Lista struct {
	ID           int32              `json:"id" db:"id"`
	UsuarioID    int32              `json:"usuario_id" db:"usuario_id"`
	Lista        string             `json:"lista" db:"lista"`
	Descricao    pgtype.Text        `json:"descricao" db:"descricao"`
	Quantidade	 int32 							`json:"quantidade" db:"quantidade"`
	CriadoEm     pgtype.Timestamptz `json:"criado_em" db:"criado_em"`
	AtualizadoEm pgtype.Timestamptz `json:"atualizado_em" db:"atualizado_em"`
}

type Usuario struct {
	ID           int32              `json:"id" db:"id"`
	Usuario      string             `json:"usuario" db:"usuario"`
	Senha        string             `json:"senha" db:"senha"`
	Nome         pgtype.Text        `json:"nome" db:"nome"`
	CriadoEm     pgtype.Timestamptz `json:"criado_em" db:"criado_em"`
	AtualizadoEm pgtype.Timestamptz `json:"atualizado_em" db:"atualizado_em"`
}
