// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.833
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/vinifrancosilva/lista_v2/web/layouts"

// TODO: migrar o html do login para fieldset do daisyui
func LoginPage() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section class=\"min-h-screen bg-gradient-to-br from-blue-50 to-purple-50 flex flex-col items-center justify-center p-4\"><div class=\"card w-full max-w-md shadow-2xl bg-white\"><div class=\"card-body p-10\"><div class=\"text-center mb-8\"><h1 class=\"text-3xl font-bold text-gray-800\">Bem-vindo(a)</h1><p class=\"text-gray-500 mt-2\">Faça login para acessar sua conta</p></div><div class=\"space-y-5\"><div class=\"form-group\"><label class=\"label\"><span class=\"label-text text-gray-600\">Usuário</span></label> <input data-bind-usuario data-ref-input_usuario data-on-load=\"$input_usuario.focus()\" type=\"text\" class=\"input input-bordered focus:input-primary focus:outline-none w-full\" id=\"usuario\" name=\"usuario\" placeholder=\"usuario\" required></div><div class=\"form-group\"><label class=\"label\"><span class=\"label-text text-gray-600\">Senha</span></label> <input data-bind-senha data-ref=\"input_senha\" data-on-keydown__window=\"evt.key === &#39;Enter&#39; &amp;&amp; @post(&#39;/login&#39;)\" type=\"password\" class=\"input input-bordered focus:input-primary focus:outline-none w-full\" id=\"senha\" name=\"senha\" placeholder=\"senha\" required></div><button data-on-click=\"@post(&#39;/login&#39;)\" class=\"btn btn-primary w-full\">Entrar\t</button></div><div class=\"divider my-4\">ou</div><p class=\"text-center text-gray-500 mt-4\">Não tem uma conta? <a href=\"#\" class=\"link link-primary\">Cadastre-se</a></p></div></div><div id=\"erro\"></div></section>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = layouts.Base("Autenticação").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
